### PR TITLE
Bug/pat 1211 fixing hidden step

### PR DESCRIPTION
**Pull request by jaimesDSG**
Fix two issues : 
- The application crash when we use the back button when the previous step was a hiddenStep
- The toolbar title was wrong when there is a hiddenStep. Fix it to avoid to count the hiddenStep.

You can use the following study to perform the test:

* environment: int-dev
* organization: jaimesdesousagomes
* study: Test study
* public user is enough. No need to log in
* task : HiddenStepTask

How to test it : just play with this task and verify the title and the back process.

Closed [PAT-1211](https://jira.devops.medable.com/browse/PAT-1211)

### CODE REVIEW

**Comment by norberto-app** [comment]
tried to run this, but it is not compiling
i get `error: cannot find symbol method checkIfShouldShowRequestPermissionRationale(String)`

Please update your branch with the latest changes from develop-medable

**Comment by pperotti-medable** [comment]
^ same error.

**Comment by Gryzor** [comment]
I added that Method, but my code is long merged and integrated afaik.

**Comment by norberto-app** [comment]
I merged latest changes from development branch, tested and is working.

**Pull request merged**
