### PR TITLE
PAT-1594: Edit button not displayed when the image is big

### PR DESCRIPTION
**Pull request by AbdallahMedable**
### Objective
- Fixed PAT-1594 [re-opened]: Edit button not displayed in the expanded image view when the captured image is big.

### How To Test
**Credentials:**
- Environment: Int-Dev
- Org: abdallahandela
- Study: Banadol

**Steps:**
**NOTE:** Before following the steps, make sure you use your phone instead of the emulator, if the captured image appears small (this is another issue PAT-1654), then don't approve this PR.
  1. Open the app and use the credentials above
  2. Join Study
  3. Take task `ReviewStep ImageCapture`
  4. Reach to ReviewStep
  5. Click on the expand button on any of the captured images

**Expected:**
The image should be displayed in a new screen, and the Edit button should be displayed below the image (see [here](https://zpl.io/a8JOWx4))

### Branches
- PAT: development
- Axon: bug/PAT-1594_fix_fullscreen_edit_button
- RS: bug/PAT-1594_fix_fullscreen_edit_button
- Cortex: development

### Links
- https://jira.devops.medable.com/browse/PAT-1594

Closes PAT-1594

### CODE REVIEW

**Comment by jaimesDSG** [comment]
Still working for me (but i never saw this issue :/)

**Comment by Gryzor** [comment]
I found a bug.

First thing first. The image full screen looks nice and the edit button looks fine too.

The issue(s) I found are:

1. The tap to expand region is too small. It needs to be twice as big (the icon remaining the same), but with at the very least, padding on every other side so at least it's 48dp or something. I've had a hard time on a small ish screen (the Nexus 5X doesn't have a huge screen) tapping the icon.
2. The Icon to CLOSE the full screen image is ridiculously small, not the icon image (I think that's small too, but if designers did it that way, that's ok), but the touching/tap area needs to be bigger than that. Out of 20 times I tried to tap the "close" button, 15 failed, no joke.
3. The **Bug**: If you tap the full screen tiny button relatively fast (rather, faster than the phone can process the message loop, which is not hard), you get two activities, stacking on top of each other.

I made a video and uploaded it to Google Drive: https://drive.google.com/open?id=137swsPrM_8nyWP7uqW4Q1WgiIqbROoaD

Notice how the image opens twice.

**Comment by AbdallahMedable** [comment]
Fixed the double tap bug in Axon MR [!670](https://gitlab.medable.com/axon/android/sdk/merge_requests/670)

**Comment by norberto-app** [comment]
tested this, and is working well, as described in the PR

**Pull request merged**
