### PR TITLE
PAT-1486: When going back to step, previous answers not saved

### PR DESCRIPTION
**Pull request by AbdallahMedable**
### Objective
- Fixed PAT-1486: When going back to step, previous answers not saved

### How To Test
**Context information**
Environment: QA
Org: Hybridstudy
Study: QA Regression

**Bug description**
When a user is on the Numeric review step and then goes back to previous steps, the values previously entered are not saved.

**Steps**
1) Launch the Pat App
2) Login to QA regression
3) Select T14- Numeric task
4) Complete all the steps and reach Review step
5) Select back until S01
6) Click Next

**Actual Result:**
Previously entered values are not saved, after optional step.

**Expected Result:**
Previously entered values should be saved.

**Note:** Please make sure you test this with a branching task as well.

### Branches
- PAT: development
- Axon: development
- RS: bug/PAT-1486_Fix_step_results_when_going_back_and_forward
- Cortex: development

### Links
- https://jira.devops.medable.com/browse/PAT-1486

Closes PAT-1486

### CODE REVIEW

**Comment by Gryzor** [comment]
I have found a way to crash this:
*  Int-dev / `neurus` / `Simple Branch With Review`
* log in with `test@ing.com` | `qpal1010` (if the password is wrong, try `qpal1100` I never remember which one it is and it's autosaved in my device). :)

1. Start the task and select Branch B.
2. Complete the number (111 for example)
3. Complete the boolean (true or false, it's irrelevant)
4. Reach Review Step, now tap the pencil to edit the branch. Switch to Branch A this time.
5. Complete Branch A Step 1 with a value (irrelevant, I used 333).
6. Branch A Step 2 is a boolean. Press SKIP and it crashes with:

```
2020-01-06 17:05:39.682 25919-25919/com.medable.axon.flask E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.medable.axon.flask, PID: 25919
    kotlin.KotlinNullPointerException
        at org.researchstack.backbone.ui.task.TaskViewModel.checkIfNewAnswerIsSkipWhilePreviousIsNot(TaskViewModel.kt:350)
        at org.researchstack.backbone.ui.task.TaskViewModel.checkForSkipDialog(TaskViewModel.kt:326)
        at org.researchstack.backbone.ui.step.fragments.BaseStepFragment.onSkipStep(BaseStepFragment.kt:22)
        at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.onSkipClicked(SurveyStepLayout.java:298)
        at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.lambda$initStepLayout$1$SurveyStepLayout(SurveyStepLayout.java:212)
        at org.researchstack.backbone.ui.step.layout.-$$Lambda$SurveyStepLayout$ES0icWl7CwtPjg_-hLLiW4ofzcs.onClick(Unknown Source:2)
        at org.researchstack.backbone.ui.views.SubmitBar.lambda$setNegativeAction$1(SubmitBar.java:116)
        at org.researchstack.backbone.ui.views.-$$Lambda$SubmitBar$rcSvA9nOUYglBbj_MAa8IoHEKio.onClick(Unknown Source:2)

```

**Comment by AbdallahMedable** [comment]
Fixed, good find :)

**Comment by Gryzor** [comment]
Ok so this failed: 

```

java.lang.IllegalStateException: nextStep must not be null

	at org.researchstack.backbone.ui.task.TaskViewModel.nextStep(TaskViewModel.kt:88)
	at org.researchstack.backbone.ui.task.TaskViewModelTest.nextStep_shouldCloseTaskFragmentWhenNextIsNull(TaskViewModelTest.kt:108)
```

**Comment by AbdallahMedable** [comment]
The UT was failing because I added the code that is inside nextStep before the if condition, Fixed that by adding it inside `else`

**Comment by Gryzor** [comment]
A bug caught by a Unit Test! :)

**Comment by Gryzor** [comment]
Ok, I found another issue:

1. Log in to `int-dev` / `neurus` / `Simple Branch With Review` (`test@ing.com` | `qpal1010` or `qpal1100`)
2. Start The Task, Select Branch B.
3. Put any valid number, and SKIP Branch B, Step 2, you're in review step.
4. Now Tap the pencil to change the branch to Branch A, accept the dialog. (It's the "Which Branch do you want to follow?" step).
5. Now complete Branch A Step 1 with any number, hit save.
6. Now SKIP Branch A Step 2.
7. Enter any number in Branch A Step 3, you're back in Review Step. 
8. Edit Branch again (like in Step 4), but select Branch B again. Accept the dialog as well.
9. Enter any number in Branch B Step 1 (I used 11)
10. Now press SKIP in Branch B Step 2. 
11. You should be in Review Step.

**Actual Result:** 
Review Step is displayed, and Branch B Step 2 (which was skipped) is *not* visible.

**Expected:** 
Review Step is displayed, and Branch B Step 2 (which was skipped) is visible and says "SKIPPED".

**Extra Bug:** 
If you edit Branch B Step 1 and Save the value, you're taken Directly to Review Step, instead of the expected Branch B Step 2. Also, Review Step now shows the skipped step correctly!


Notice how the last step should be Branch B, Step 2 but it's not there:
Screenshot_1578333976

**Comment by AbdallahMedable** [comment]
@Gryzor Fixed!
FYI these two issues are already happening on develop, but anyway I fixed them :)

**Comment by Gryzor** [comment]
ok, i found another one... (sorry) :)


Same Study/Env/Task


1. Start with Branch B, complete the Branch B Step 1, and SKIP Branch B Step 2
2. In ReviewStep, edit the branch and go to branch A. 
3. In Branch A: Complete Step 1 (any value), and skip the next two steps. 

You're back in ReviewStep and Branch A Step 3 is *not visible*.

Another side-issue that I noticed, is that Branch A Step 3, tells me "Do you want to skip this step?" And It should not, because I never completed Branch A Step 3 before...

**Comment by AbdallahMedable** [comment]
@Gryzor Fixed! And also fixed showing the Skipped dialog for steps that aren't taken before, it was actually implemented incorrectly

**Comment by AbdallahMedable** [comment]
I can't believe it 😂
Please merge this before any other issues appear :D

**Pull request merged**
